Qol
sarcophagus-org/sarcophagus-v2-app pull request #162
Opened 2022-11-03 21:09 UTC by katien

2022-11-04 12:04 UTC, DarksightKellar approved these changes

2022-11-04 12:04 UTC, DarksightKellar commented on README.md
> +
Whew this is thorough! 🙌🏾

2022-11-04 12:06 UTC, DarksightKellar requested changes
Looks good! There's linter complaints though causing netlify build to fail

2022-11-04 14:12 UTC, sethhrbek approved these changes

2022-11-04 14:12 UTC, sethhrbek commented on README.md
> +
The arch will automatically be pointed at arLocal when running on the local network (doesn't hurt to still have this note, but user doesn't need to take any action for this)

2022-11-04 14:13 UTC, sethhrbek commented
these are the linter errors --

![image](https://user-images.githubusercontent.com/43755993/199996203-e5edbaf5-aec8-4b18-8eb9-7c36648fb2b2.png)

2022-11-07 14:21 UTC, DarksightKellar approved these changes

2022-11-07 15:55 UTC, merged